language: node_js
node_js:
- '4'
- '5'
- '6'
- '7'
after_script: ./node_modules/.bin/lab -r lcov | ./node_modules/.bin/coveralls
notifications:
  slack:
    secure: PpGsmZqkOsNNh+qdZAUhtYCLwVgsJUKqun10qomXbRgalubWPNaV3Wa4a6CLxq3IZwJ2jlcDYg7bwohqooaHB8eXZJ57kRad4IVtHTXkT3m7q5Tff3Wmg/T93CzhGoiCO73xPcKiC+yM6afdP+CstWDIVXIk+i+cb4+XbZ32laI=
